name: Lint

on:
  # Trigger the workflow on pull request,
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

permissions:
      actions: read
      contents: write
      checks: write

jobs:
  run-linters:
    name: Run linters
    runs-on: windows-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: 'x86' 

      - name: Install dependencies
        run: | 
          py  -3.7-32 -m pip install --upgrade pip
          py  -3.7-32 -m pip install -r requirements/requirements_dev.txt
          py  -3.7-32 -m pip install -r requirements/requirements_dev.txt --target ./src/
          py  -3.7-32 -m pip install black flake8

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          flake8: true
          