name: Lint

on:
  # Trigger the workflow on pull request,
  pull_request:
    # The branches below must be to the branches below
    branches: [ master ]
    types:
      - opened
      - synchronize
      - reopened

permissions:
    contents: write
    checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run-linters:
    name: Run linters
    runs-on: windows-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          #ref: ${{ github.event.pull_request.head.sha }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: 'x86' 

      - name: Install dependencies
        run: | 
          py  -3.7-32 -m pip install --upgrade pip
          py  -3.7-32 -m pip install -r requirements/requirements_dev.txt
          py  -3.7-32 -m pip install -r requirements/requirements_dev.txt --target ./src/
          py  -3.7-32 -m pip install black flake8

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          flake8: true
          